

import "./globals.css";
import Footer from "@/Components/Footer/Footer";
import { ThemeContextProvider } from "@/Components/Context/ThemeContext";
import ThemeProvider from "@/Components/providers/ThemeProvider";
import TransitionProvider from "@/Components/providers/TransitionProvider";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        
        <ThemeContextProvider>
          <ThemeProvider>
             
            <TransitionProvider>
              <div className="Container">

                {children}
              <Footer/>
              </div>
            </TransitionProvider>
              

          </ThemeProvider>
        </ThemeContextProvider>
       
       
      </body>
    </html>
  );
}
